version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env # required line: POSTGRES_PASSWORD="..."
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
